"""add created_at and updated_at to all tables

Revision ID: 0c251f2b69bc
Revises: 20bcd9e76f05
Create Date: 2026-05-05 21:08:26.371587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c251f2b69bc'
down_revision: Union[str, Sequence[str], None] = '20bcd9e76f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('board_members', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('boards', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('boards', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cards', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('cards', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('checklists', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('checklists', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('columns', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('columns', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tags', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task_assignees', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('task_assignees', 'created_at')
    op.drop_column('tags', 'updated_at')
    op.drop_column('tags', 'created_at')
    op.drop_column('comments', 'updated_at')
    op.drop_column('columns', 'updated_at')
    op.drop_column('columns', 'created_at')
    op.drop_column('checklists', 'updated_at')
    op.drop_column('checklists', 'created_at')
    op.drop_column('cards', 'updated_at')
    op.drop_column('cards', 'created_at')
    op.drop_column('boards', 'updated_at')
    op.drop_column('boards', 'created_at')
    op.drop_column('board_members', 'created_at')
    op.drop_column('attachments', 'created_at')
    # ### end Alembic commands ###
